routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

/* display and redirect routes */

Route::get('/banner/embed/{id}', 'BannersController@show');
Route::get('/advert/{id}', 'BannersController@redirect');

Route::any('/login', 'UsersController@login')->name('login');
Route::any('/register', 'UsersController@register')->name('register');

Route::get('/logout', 'UsersController@logout');

Route::group(['middleware' => ['auth', 'admin']], function(){
    Route::prefix('admin')->group(function () {
        Route::get('/', function(){
            return view('admin.dashboard');
        });

        Route::get('/stats', 'Admin\StatsController@index');
        Route::get('/stats/{id}', 'Admin\StatsController@show');
        Route::get('/stats/{id}/{banner}', 'Admin\StatsController@showBanner');

        // clients resource
        Route::resource('clients', 'Admin\ClientsController');
        // banners resource
        Route::resource('banners', 'Admin\BannersController');
        // affiliators resource
        Route::resource('affiliators','Admin\AffiliatorController');
    });
});

Route::group(['middleware' => ['auth', 'influencer']], function(){
    Route::prefix('influencer')->group(function(){
        Route::get('/', 'Influencer\StatsController@index');
        Route::get('/banners', 'Influencer\BannerController@index');
        Route::get('/account', 'Influencer\AccountController@show');
        Route::post('/account', 'Influencer\AccountController@update');
    });
});

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Client;

class Banner extends Model
{
    protected $guarded = ['id'];

    public function author(){
        return $this->hasOne('App\User', 'id', 'created_by');
    }

    public function client(){
        return $this->hasOne('App\Client', 'id', 'client_id');
    }

    public function publisher(){
        return $this->hasOne('App\Client', 'id', 'publisher_id');
    }
}

app/Http/Controllers/Admin/BannersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

use App\User;
use App\Banner;
use App\Client;
use App\Affiliator;

class BannersController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $count = $request->input('count', 10);
        $banners = Banner::paginate($count);
        return view('admin.banners.index', ['banners' => $banners]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::all();
        $affiliators = User::where('role', 'influencer')->get();
        return view('admin.banners.create', ['clients' => $clients, 'affiliators' => $affiliators]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // process upload image
        $path = "";
        $image = $request->image;
        if($request->hasFile('image')){
            $path = $image->store('images', 'public');
        }

        $banner = Banner::create([
            'title' => $request->title,
            'link' => $request->link,
            'image' => $path,
            'publisher_id' => $request->publisher_id,
            'client_id' => $request->client_id,
            'width' => $request->input('width', '728'),
            'height' => $request->input('height', '90'),
            'affiliator' => $request->input('affiliator'),
            'price' => $request->input('price'),
            'created_by' => Auth::user()->id,
            'updated_by' => Auth::user()->id,
            'status' => $request->input('status', false) ? true : false
        ]);

        return redirect('/admin/banners/'.$banner->id.'/edit');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $banner = Banner::find($id);
        return view('admin.banners.show', ['banner' => $banner]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $banner = Banner::find($id);
        $clients = Client::all(['id', 'name']);
        $affiliators = Affiliator::all();

        return view('admin.banners.edit', ['banner' => $banner, 'clients' => $clients, 'affiliators' => $affiliators]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // process image
        $image = $request->image;
        $path = "";
        if($request->hasFile('image')){
            $path = $image->store('images', 'public');
        }

        $banner = Banner::find($id);

        $banner->title = $request->title;
        $banner->link = $request->link;
        
        if(empty($path) != false){
            $banner->image = $path;
        }

        $banner->client_id = $request->client_id;
        $banner->publisher_id = $request->publisher_id;
        $banner->updated_by = Auth::user()->id;
        $banner->width = $request->input('width', '728');
        $banner->height = $request->input('height', '90');
        $banner->price = $request->input('price', 0);
        $banner->status = $request->input('status', false) ? true : false;
        $banner->affiliator = $request->input('affiliator');
        
        $banner->save();

        return redirect('/admin/banners/'.$banner->id.'/edit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $banner = Banner::find($id);
        $banner->delete();
        return redirect('/admin/banners')->with('message', 'Banner successfully deleted');
    }
}

app/Http/Controllers/BannersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Banner;
use App\Activity;
use App\Stats;
use App\Location;

class BannersController extends Controller
{
    public function show(Request $request, $id){
        $banner = Banner::find($id); // find banner with id
        if($banner != null){
            $location = new Location(request()->ip());

            Stats::create([
                "ip" => $location->getIp(),
                "country" => $location->getCountry(),
                "country_code" => $location->getCountryCode(),
                "city" => $location->getCity(),
                "region" => $location->getRegion(),
                "isp" => $location->getISP(),
                "timezone" => $location->getTimezone(),
                "affiliator" => $request->input("affiliator", "0"),
                "ads_id" => $id
            ]);



            $table->ipAddress('ip');
            $table->string('country')->nullable();
            $table->string('country_code')->nullable();
            $table->string('city')->nullable();
            $table->string('region')->nullable();
            $table->string('isp')->nullable();
            $table->string('timezone')->nullable();
            $table->bigInteger('affiliator');
            $table->bigInteger('ads_id');

            return view('embed', ['banner' => $banner]);
        }else{
            return "Banner doesn't exists.";
        }
    }

    public function redirect(Request $request, $id){
        $banner = Banner::find($id); // find banner with id
        if($banner != null){
            $location = new Location(request()->ip());

            Stats::create([
                "ip" => $location->getIp(),
                "country" => $location->getCountry(),
                "country_code" => $location->getCountryCode(),
                "city" => $location->getCity(),
                "region" => $location->getRegion(),
                "isp" => $location->getISP(),
                "timezone" => $location->getTimezone(),
                "affiliator" => $request->input("affiliator", "0"),
                "ads_id" => $id
            ]);
            
            return redirect()->away($banner->link);
        }else{
            return "Banner doesn't exists.";
        }    
    }
}

app/Http/Controllers/Influencer/BannerController.php
<?php

namespace App\Http\Controllers\Influencer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Banner;
use App\User;

class BannerController extends Controller
{
    public function index(Request $request){
        $count = $request->input("count", 10);
        $banners = Banner::where()->paginate($count);

        return view('influencer.banners.index');
    }
}

resources/views/admin/banners/create.blade.php
@extends('partials.admin')

@section('title', 'Create a new Banner')

@section('content')

<div class="row">
    <div class="col-md-8">
        <h3>Create a Banner</h3>
        <hr>
        {{ Form::open(['route' => 'banners.store', 'files' => true]) }}
            <div class="form-group">
                <label for="title">Title:</label>
                {{ Form::text('title', null, ['class' => 'form-control', 'id' => 'title']) }}
            </div>
            <div class="form-group">
                <label for="link">Link:</label>
                {{ Form::text('link', null, ['class' => 'form-control', 'id' => 'link']) }}
            </div>
            <div class="form-group">
                <label for="image">Image:</label>
                {{ Form::file('image') }}
            </div>
            <div class="form-group">
                <label for="width">Width:</label>
                {{ Form::text('width', '728', ['class' => 'form-control', 'id' => 'width']) }}
                <br>
                <label for="height">Height:</label>
                {{ Form::text('height', '90', ['class' => 'form-control', 'id' => 'height']) }}
            </div>
            
            <div class="form-group">
                <label for="client">client:</label>
                <select name="client_id" id="client" class="form-control">
                    @foreach($clients as $client)
                        <option value="{{ $client->id }}" selected>{{ $client->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="publisher">Publisher:</label>
                <select name="publisher_id" id="publisher" class="form-control">
                    @foreach($clients as $client)
                        <option value="{{ $client->id }}">{{ $client->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="affiliator">Affiliator:</label>
                <select name="affiliator" id="affiliator" class="form-control">
                    @foreach($affiliators as $affiliator)
                        <option value="{{ $affiliator->id }}">{{ $affiliator->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="price">Price</label>
                {{ Form::text("price", null, ['class' => 'form-control', 'id' => 'price']) }}
            </div>

            <div class="form-group">
                <label for="status">Status:</label>
                {{ Form::select('status', ['0' => 'unpublished', '1' => 'published'], '1', ['class' => 'form-control','id' => 'status']) }}
            </div>
            <div class="form-group">
                {{ Form::submit('Save', ['class' => 'btn btn-success']) }}
            </div>
        {{ Form::close() }}
    </div>
</div>
@endsection

resources/views/admin/banners/edit.blade.php
@extends('partials.admin')

@section('title', 'Edit a Banner')

@section('content')

<div class="row">
    <div class="col-md-8">
        <h3>Edit Banner</h3>
        <hr>
        {{ Form::model($banner, ['route' => ['banners.update', $banner->id], 'files' => true]) }}
            <input type="hidden" name="_method" value="PUT" />
            <div class="form-group">
                <label for="title">Title:</label>
                {{ Form::text('title', null, ['class' => 'form-control', 'id' => 'title']) }}
            </div>
            <div class="form-group">
                <label for="link">Link:</label>
                {{ Form::text('link', null, ['class' => 'form-control', 'id' => 'link']) }}
            </div>
            <div class="form-group">
                <label for="image">Image:</label>
                {{ Form::file('image') }}
            </div>

            <div class="form-group">
                <label for="width">Width:</label>
                {{ Form::text('width', '728', ['class' => 'form-control', 'id' => 'width']) }}
                <br>
                <label for="height">Height:</label>
                {{ Form::text('height', '90', ['class' => 'form-control', 'id' => 'height']) }}
            </div>
            <div class="form-group">
                <label for="client">client:</label>
                <select name="client_id" id="client" class="form-control">
                    @foreach($clients as $client)
                        @if($client->id == $banner->client_id)
                            <option value="{{ $client->id }}" selected>{{ $client->name }}</option>
                        @else
                            <option value="{{ $client->id }}" selected>{{ $client->name }}</option>
                        @endif
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="publisher">Publisher:</label>
                <select name="publisher_id" id="publisher" class="form-control">
                    @foreach($clients as $client)
                        @if($client->id == $banner->client_id)
                            <option value="{{ $client->id }}" selected>{{ $client->name }}</option>
                        @else
                            <option value="{{ $client->id }}" selected>{{ $client->name }}</option>
                        @endif
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="affiliator">Affiliator:</label>
                <select name="affiliator" id="affiliator" class="form-control">
                    @foreach($affiliators as $affiliator)
                        @if($affiliator->id == $banner->affilitor)
                            <option value="{{ $$affiliator->id }}" selected>{{ $$affiliator->last_name }} {{ $$affiliator->first_name }}</option>
                        @else
                            <option value="{{ $affiliator->id }}">{{ $affiliator->last_name }} {{ $affiliator->first_name}}</option>
                        @endif
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="price">Price</label>
                {{ Form::text("price", null, ['class' => 'form-control', 'id' => 'price']) }}
            </div>

            <div class="form-group">
                <label for="status">Status:</label>
                {{ Form::select('status', ['0' => 'unpublished', '1' => 'published'], '1', ['class' => 'form-control','id' => 'status']) }}
            </div>
            <div class="form-group">
                {{ Form::submit('Save', ['class' => 'btn btn-success']) }}
            </div>
        {{ Form::close() }}
    </div>
    <div class="col-md-4">
        <h3>Banner</h3>
        <div class="banner form-group">
            <img src="{{ asset('storage/'.$banner->image) }}" alt="" class="img-responsive">
        </div>
        <hr>
            <button class="btn btn-primary" data-toggle="modal" data-target="#htmlembed">Embed HTML Code</button>
        <hr>
        {{ Form::open(['route' => ['banners.destroy', $banner->id]]) }}
            {{ Form::hidden('_method', 'DELETE') }}
            {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
        {{ Form::close() }}
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="htmlembed">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Banner HTML Code</h4>
                </div>
                <div class="modal-body">
                    <span>Code iframe HTML</span>
                    <code>
                            &lt;iframe src=&quot;http://ads.yegob.com/banner/embed/1&quot; frameborder=&quot;0&quot; width=&quot;{{ $banner->width }}&quot; height=&quot;{{ $banner->height}}&quot; scrolling=&quot;no&quot;&gt;&lt;/iframe&gt;
                    </code>
                    <hr>
                    <span>Lien Affiliator:</span>
                    <code>
                        http://ads.yegob.com/advert/{{ $banner->id }}?affiliator={{ $banner->affiliator }}
                    </code>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/banners/index.blade.php
@extends('partials.admin')

@section('title', 'List all banners')

@section('content')

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>title</th>
                    <th>Client</th>
                    <th>Publisher</th>
                    <th>Created By</th>
                    <th>Created At</th>
                    <th>Status</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                @foreach($banners as $banner)
                    <tr>
                        <th>
                            <a href="{{ route('banners.edit', ['id' => $banner->id ]) }}">{{ $banner->title }}</a>
                        </th>
                        <th>
                            <a href="{{ route('clients.edit', ['id' => $banner->client->id ] ) }}">
                                {{ $banner->client->name }}
                            </a>
                        </th>
                        <th>
                            <a href="{{ route('clients.edit', ['id' => $banner->client->id ] ) }}">
                                {{ $banner->publisher->name }}
                            </a>
                        </th>
                        <th>{{ $banner->author->name }}</th>
                        <th>{{ $banner->created_at }}</th>
                        <th>{{ $banner->status }}</th>
                        <th>
                            <a href="{{ route('banners.edit', ['id' => $banner->id ]) }}" class="btn btn-info">edit</a>
                        </th>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@endsection

resources/views/admin/banners/show.blade.php
@extends('partials.admin')

@section('title', 'Create a new Banner')

@section('content')

<h2>Create a new banner</h2>

@endsection