routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

/* display and redirect routes */

Route::get('/banner/embed/{id}', 'BannersController@show');
Route::get('/advert/{id}', 'BannersController@redirect');

Route::any('/login', 'UsersController@login')->name('login');
Route::any('/register', 'UsersController@register')->name('register');

Route::get('/logout', 'UsersController@logout');

Route::group(['middleware' => ['auth', 'admin']], function(){
    Route::prefix('admin')->group(function () {
        Route::get('/', function(){
            return view('admin.dashboard');
        });

        Route::get('/stats', 'Admin\StatsController@index');
        Route::get('/stats/{id}', 'Admin\StatsController@show');
        Route::get('/stats/{id}/{banner}', 'Admin\StatsController@showBanner');

        // clients resource
        Route::resource('clients', 'Admin\ClientsController');
        // banners resource
        Route::resource('banners', 'Admin\BannersController');
        // affiliators resource
        Route::resource('affiliators','Admin\AffiliatorController');
    });
});

Route::group(['middleware' => ['auth', 'influencer']], function(){
    Route::prefix('influencer')->group(function(){
        Route::get('/', 'Influencer\StatsController@index');
        Route::get('/banners', 'Influencer\BannerController@index');
        Route::get('/account', 'Influencer\AccountController@show');
        Route::post('/account', 'Influencer\AccountController@update');
    });
});

app/Stats.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stats extends Model
{
    //
    protected $table = "stats";
    protected $guarded = ["id"];

    protected $hidden = ['password'];
}

app/Http/Controllers/Admin/StatsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Stats;
use App\Affiliator;
use Carbon\Carbon;

class StatsController extends Controller
{
    //
    public function __construct(){

    }

    public function index(Request $request){
        $search = $request->input('query', '');
        $affiliators = Affiliator::all();
        return view('admin.stats.index', ["affiliators" => $affiliators]);
    }

    public function show(Request $request, $id){
        $now = Carbon::now();
        $start = $now->startOfWeek()->toDateString(). " 00:00:00";        ;
        $end = $now->startOfWeek()->addWeek()->toDateString(). " 00:00:00";

        $stats = Stats::where("affiliator","=", $id)
            ->where("created_at", ">=", $start)
            ->where("created_at", "<", $end)
            ->get()
            ->groupBy(function($item){
                    return $item->created_at->format('d-M-y');
            })->toArray();

            return view('admin.stats.show', ['stats' => $stats ]);
    }

    public function showBanner(Request $request, $id, $banner){
        $stats = Stats::where("affiliator", $id);


    }
}

app/Http/Controllers/Influencer/StatsController.php
<?php

namespace App\Http\Controllers\Influencer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

use App\Stats;
use App\User;

class StatsController extends Controller
{
    public function index(Request $request){
        $now = Carbon::now();
        $start = $now->startOfMonth()->toDateString(). " 00:00:00";        ;
        $end = $now->endOfMonth()->addDay()->toDateString(). " 00:00:00";

        $stats = Stats::where("affiliator","=", Auth::user()->id)
            ->where("created_at", ">=", $start)
            ->where("created_at", "<", $end)
            ->get()
            ->groupBy(function($item){
                    return $item->created_at->format('d-M-y');
            })->toArray();
            
        return view('influencer.stats.index', ['stats' => $stats]);
    }
}

resources/views/admin/stats/index.blade.php
@extends('partials.admin')

@section('title', 'List all banners')

@section('content')

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                @foreach($affiliators as $affiliator)
                    <tr>
                        <th>
                            <a href="{{ $affiliator->id }}">{{ $affiliator->first_name }}</a>
                        </th>
                        <th>
                            <a href="{{ route('affiliators.edit', ['id' => $affiliator->id ] ) }}">
                                {{ $affiliator->last_name }}
                            </a>
                        </th>
                        <th>
                            {{ $affiliator->email }}
                        </th>
                        <th>
                            <a href="{{ route('affiliators.edit', ['id' => $affiliator->id ]) }}" class="btn btn-info">edit</a>
                            <a href="{{ url('/admin/stats/'.$affiliator->id) }}" class="btn btn-info">Show Statistics</a>
                        </th>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@endsection

resources/views/admin/stats/show.blade.php
@extends('partials.admin')

@section('title', 'Statistics')

@section('content')

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Date: </th>
                    <th>Total Views</th>
                    <th>Revenues: </th>
                </tr>
            </thead>
            <tbody>
                @foreach(array_reverse($stats) as $date => $stat)
                <tr>
                    <td>{{ $date }}</td>
                    <td>{{ count($stat) }} views</td>
                    <td>0.0 RWF</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@endsection